[workspace]
# Try
# require version 2 to avoid "feature" additiveness for dev-dependencies
# https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2
resolver = "2"

members = [
    "crates/*", "examples/*",
]

[workspace.package]
edition = "2021"
version = "0.1.0"
readme = "README.md"

[profile.dev]
debug = 0 # Speed up compilation time and not necessary.
