[workspace]
# Try
# require version 2 to avoid "feature" additiveness for dev-dependencies
# https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2
resolver = "2"

members = [
    "crates/*",
    "examples/*",
    "xtask",
]

[workspace.package]
edition = "2021"
version = "0.1.0"
readme = "README.md"

[workspace.dependencies]
clap = { version = "4.5.4", features = ["derive"] }
dotenv = "0.15.0"
env_logger = "0.11.3"
log = "0.4.21"
rand = "0.8.5"
rstest = "0.19.0"
rmp-serde = "1.3.0"
derive-new = { version = "0.6.0", default-features = false }

serde = { version = "1.0.200", default-features = false, features = [
    "derive",
    "alloc",
] } # alloc is for no_std, derive is needed
serde_json = "1.0.64"

thiserror = "1.0.30"
reqwest = "0.12.4"

[profile.dev]
debug = 0 # Speed up compilation time and not necessary.
