[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
edition.workspace = true
name = "guide"
publish = false
version.workspace = true

[dependencies]
tracel = {path = "../../crates/tracel", features = ["heat-sdk"]}
burn = { version = "0.13.2", features = ["vision", "wgpu", "train"]}

# Serialization
log = {workspace = true}
serde = {workspace = true, features = ["std", "derive"]}
