[package]
authors = ["Tracel Technologies Inc."]
categories = ["development-tools"]
description = "Tracel SDK."
keywords = ["tracel", "heat", "burn", "sdk"]
edition.workspace = true
license.workspace = true
name = "tracel"
readme.workspace = true
repository = "https://github.com/tracel-ai/tracel/tree/main/crates/tracel"
version.workspace = true
rust-version = "1.79"

[features]
default = ["heat-sdk"]
heat-sdk = ["dep:heat-sdk", "dep:heat-sdk-cli-macros"]
heat-sdk-cli = ["dep:heat-sdk-cli", "heat-sdk-cli-macros/build-cli"]

[dependencies]
heat-sdk = { path = "../heat-sdk", version = "0.1.0", optional = true }
heat-sdk-cli = { path = "../heat-sdk-cli", version = "0.1.0", optional = true }
heat-sdk-cli-macros = { path = "../heat-sdk-cli-macros", version = "0.1.0", optional = true }
